"""Cwl added

Revision ID: 1c418574fecc
Revises: 250b2ac6c951
Create Date: 2020-08-26 08:02:31.767676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1c418574fecc"
down_revision = "250b2ac6c951"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clan_war_league",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("tag", sa.String(length=64), nullable=True),
        sa.Column("season", sa.String(length=12), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("war", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("clan_war_league_id", sa.Integer(), nullable=True)
        )
        batch_op.create_foreign_key(
            "clan_war_league_war", "clan_war_league", ["clan_war_league_id"], ["id"]
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("war", schema=None) as batch_op:
        batch_op.drop_constraint("clan_war_league_war", type_="foreignkey")
        batch_op.drop_column("clan_war_league_id")

    op.drop_table("clan_war_league")
    # ### end Alembic commands ###
