"""Percentage Added to War

Revision ID: 250b2ac6c951
Revises: e6270932046b
Create Date: 2020-08-17 21:20:41.650726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '250b2ac6c951'
down_revision = 'e6270932046b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('war', sa.Column('clan_percentage', sa.Float(), nullable=True))
    op.add_column('war', sa.Column('enemy_percentage', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('war', 'enemy_percentage')
    op.drop_column('war', 'clan_percentage')
    # ### end Alembic commands ###
