"""Init

Revision ID: 28e948def274
Revises: 
Create Date: 2020-07-26 10:53:55.058254

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28e948def274'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member',
    sa.Column('id', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('th_level', sa.Integer(), nullable=True),
    sa.Column('king_level', sa.Integer(), nullable=True),
    sa.Column('queen_level', sa.Integer(), nullable=True),
    sa.Column('warden_level', sa.Integer(), nullable=True),
    sa.Column('royal_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_member_name'), 'member', ['name'], unique=True)
    op.create_table('mode',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('war',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enemy', sa.String(length=64), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('victory', sa.Boolean(), nullable=True),
    sa.Column('enemy_clan_level', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_war_end_time'), 'war', ['end_time'], unique=False)
    op.create_index(op.f('ix_war_start_time'), 'war', ['start_time'], unique=False)
    op.create_index(op.f('ix_war_victory'), 'war', ['victory'], unique=False)
    op.create_table('battle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enemy_tag', sa.String(length=12), nullable=False),
    sa.Column('enemy_th_level', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.String(length=12), nullable=False),
    sa.Column('member_th_level', sa.Integer(), nullable=False),
    sa.Column('mode_id', sa.Integer(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('percentage', sa.Float(), nullable=False),
    sa.Column('war_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['mode_id'], ['mode.id'], ),
    sa.ForeignKeyConstraint(['war_id'], ['war.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_in_war',
    sa.Column('member_id', sa.String(length=12), nullable=True),
    sa.Column('war_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['war_id'], ['war.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_in_war')
    op.drop_table('battle')
    op.drop_index(op.f('ix_war_victory'), table_name='war')
    op.drop_index(op.f('ix_war_start_time'), table_name='war')
    op.drop_index(op.f('ix_war_end_time'), table_name='war')
    op.drop_table('war')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_table('user')
    op.drop_table('mode')
    op.drop_index(op.f('ix_member_name'), table_name='member')
    op.drop_table('member')
    # ### end Alembic commands ###
