"""Added Member and CWL Table

Revision ID: 49a6e349fe34
Revises: 1c418574fecc
Create Date: 2020-09-02 20:28:21.078372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49a6e349fe34'
down_revision = '1c418574fecc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('member_in_clan_war',
    sa.Column('member_id', sa.String(length=12), nullable=True),
    sa.Column('clan_war_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['clan_war_id'], ['clan_war_league.id'], ),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_in_clan_war')
    # ### end Alembic commands ###
