"""Added Missing Value in Member

Revision ID: 6ca57bae53c6
Revises: cd3daf7a56e3
Create Date: 2020-07-11 22:09:05.952836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ca57bae53c6'
down_revision = 'cd3daf7a56e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member', sa.Column('king_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('member', 'king_level')
    # ### end Alembic commands ###
