"""wars

Revision ID: c2b06a17610c
Revises: 6ca57bae53c6
Create Date: 2020-07-22 06:11:36.817546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b06a17610c'
down_revision = '6ca57bae53c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('war',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enemy', sa.String(length=64), nullable=True),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('victory', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_war_end_time'), 'war', ['end_time'], unique=False)
    op.create_index(op.f('ix_war_start_time'), 'war', ['start_time'], unique=False)
    op.create_index(op.f('ix_war_victory'), 'war', ['victory'], unique=False)
    op.create_table('member_in_war',
    sa.Column('member_id', sa.String(length=12), nullable=True),
    sa.Column('war_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['member.id'], ),
    sa.ForeignKeyConstraint(['war_id'], ['war.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_in_war')
    op.drop_index(op.f('ix_war_victory'), table_name='war')
    op.drop_index(op.f('ix_war_start_time'), table_name='war')
    op.drop_index(op.f('ix_war_end_time'), table_name='war')
    op.drop_table('war')
    # ### end Alembic commands ###
