"""Added Stars to War Data

Revision ID: e6270932046b
Revises: e6fbb105e89d
Create Date: 2020-08-17 21:16:18.663691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6270932046b'
down_revision = 'e6fbb105e89d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('war', sa.Column('clan_stars', sa.Integer(), nullable=True))
    op.add_column('war', sa.Column('enemy_stars', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('war', 'enemy_stars')
    op.drop_column('war', 'clan_stars')
    # ### end Alembic commands ###
