"""Added Member and Enemy Position on Map

Revision ID: e6fbb105e89d
Revises: ed91471a1979
Create Date: 2020-08-17 21:08:40.722563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6fbb105e89d'
down_revision = 'ed91471a1979'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battle', sa.Column('enemy_position', sa.Integer(), nullable=False))
    op.add_column('battle', sa.Column('member_position', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('battle', 'member_position')
    op.drop_column('battle', 'enemy_position')
    # ### end Alembic commands ###
