"""Added Teamsize

Revision ID: ed91471a1979
Revises: 5869b52232f5
Create Date: 2020-08-13 13:31:47.884062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed91471a1979'
down_revision = '5869b52232f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('war', sa.Column('size', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('war', 'size')
    # ### end Alembic commands ###
